min_version = "2024.11.32"

[tools]
tuist = "4.36.0"
swiftformat = "0.54"
swiftgen = "6.6.3"

[settings]
task_run_auto_install = false
exec_auto_install = false
experimental = true
lockfile = true

[task_config]
includes = ["mise-tasks"]
